version: '2'
services:
  remote_user:
    #build: .
    image: quay.io/tamu_cpt/remote-user-proxy:latest
    links:
      - apollo:target
    ports:
      - "9998:80"
    environment:
      BACKEND_URL: "http://target:8080"
      REMOTE_USER: admin@local.host

  apollo:
    image: dockerapollo_apollo
    links:
      - db
      - chado
    ports:
      - "9999:8080"
    environment:
      CONTEXT_PATH: galaxy/gxc_proxy/apollo
      WEBAPOLLO_DB_USERNAME: postgres
      WEBAPOLLO_DB_PASSWORD: password
      WEBAPOLLO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_DB_URI: "jdbc:postgresql://db/postgres"
      WEBAPOLLO_CHADO_DB_USERNAME: postgres
      WEBAPOLLO_CHADO_DB_PASSWORD: password
      WEBAPOLLO_CHADO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_CHADO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_CHADO_DB_URI: "jdbc:postgresql://chado/postgres"
    volumes:
      - "./data:/data"
  db:
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: password
  chado:
    image: erasche/chado:latest
    environment:
      - POSTGRES_PASSWORD=password
      # The default chado image would try to install the schema on first run
      #- INSTALL_CHADO_SCHEMA=0
    volumes:
      - /var/lib/postgresql/9.4/
