version: '2'
services:
  remote_user:
    #build: .
    image: quay.io/tamu_cpt/remote-user-proxy:latest
    links:
      - echo:target
    ports:
      - "80"
    environment:
      BACKEND_URL: "http://target:8000"
      REMOTE_USER: user@example.com
  echo:
    image: quay.io/tamu_cpt/httpbin:latest
